export const data = [
  {
    title: "kindergarten",
    image: "/pics/kinder.png",
    category: "Html - css - java script - react.js - firebase - sass",
    link: "https://kindergarten-33db4.web.app/",
    code: "https://github.com/93amrkakashi/kinder",
  },
  {
    title: "SooQ",
    image: "/pics/sooq.png",
    category: "Html - css - java script - react.js - firebase - sass",
    link: "https://shopping-app-cd303.web.app/",
    code: "https://github.com/93amrkakashi/sooq",
  },
  {
    title: "TweeTs",
    image: "/pics/tweets.png",
    category: "Html - css - java script - react.js - firebase - sass",
    link: "https://social-app-dfc91.web.app/",
    code: "https://github.com/93amrkakashi/tweet-app",
  },
  {
    title: "Youtube Clone",
    image: "/pics/youtube.png",
    category: "Html - css - java script - react.js - firebase - sass- api",
    link: "https://tweets-97126.web.app/",
    code: "https://github.com/93amrkakashi/my-tube",
  },
  {
    title: "MP3 Player",
    image: "/pics/mp3.png",
    category: "Html - css - java script - type script ",
    link: "https://93amrkakashi.github.io/mp3player/",
    code: "",
  },
  {
    title: "Portfolio TS Chakra",
    image: "/pics/portfolio-ts.png",
    category: "Html - css - type script - java script - react.js - firebase - chakra ui",
    link: "https://next-type-je76.vercel.app/",
    code: "https://github.com/93amrkakashi/portfolio-nextjs-ts",
  },
  {
    title: "The Queen's English",
    image: "/pics/game.png",
    category: "Html - css - java script - react.js",
    link: "https://jazzy-semifreddo-e05591.netlify.app/",
    code: "https://github.com/93amrkakashi/queen-en-task",
  },
  {
    title: "Learning Management system",
    image: "/pics/lms.png",
    category: "Html - css - java script - type script ",
    link: "https://93amrkakashi.github.io/LMS-website/home.html",
    code: "https://github.com/93amrkakashi/LMS-website",
  },
  {
    title: "ToDo App PWA",
    image: "/pics/todo.png",
    category: "Html - css - type script - java script - react.js - bootstarp",
    link: "https://todo-react-delta-one.vercel.app/",
    code: "https://github.com/93amrkakashi/todo-react",
  },
  {
    title: "Quiz App",
    image: "/pics/quiz.png",
    category: "Html - css - java script - type script ",
    link: "https://93amrkakashi.github.io/quiz-app/",
    code: "https://github.com/93amrkakashi/quiz-app",
  },
  {
    title: "currency-exchange App",
    image: "/pics/curr.png",
    category: "Html - css - java script - type script ",
    link: "https://93amrkakashi.github.io/currency-exchange/",
    code: "https://github.com/93amrkakashi/currency-exchange",
  },
  {
    title: "Azkar App",
    image: "/pics/azkar.png",
    category: "Html - css - java script - type script ",
    link: "https://93amrkakashi.github.io/azkar/",
    code: "https://github.com/93amrkakashi/azkar",
  },
];
